backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: "pedals"
    label: "Pedals"
    folder: "src/pages/pedals"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "pedals-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      # - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "PayPal Embed Code", name: "payPal", widget: "text" }
      - { label: "Pedal Image", name: "pedalimage", widget: "image" }
      - {
          label: "Media",
          name: "media",
          widget: list,
          fields: [{ label: Media Item, name: mediaItem, widget: text }],
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Video URL, name: videoUrl, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
      - file: "src/pages/bio/index.md"
        label: "Bio Page"
        name: "bio"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "bio-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: "image", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/dealers/index.md"
        label: "Dealers Page"
        name: "dealers"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "dealers-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Domestic Dealers,
              name: domestic,
              widget: object,
              fields: [{ label: Content, name: content, widget: markdown }],
            }
          - {
              label: International Dealers,
              name: international,
              widget: object,
              fields: [{ label: Content, name: content, widget: markdown }],
            }
      - file: "src/pages/press/index.md"
        label: "Press Page"
        name: "press"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "press-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Press Items,
              name: items,
              widget: list,
              fields:
                [
                  { label: Publication, name: publication, widget: string },
                  { label: Image, name: image, widget: "image" },
                  { label: Url, name: url, widget: string },
                  { label: Text, name: text, widget: text },
                ],
            }
      - file: "src/pages/artists/index.md"
        label: "Artists Page"
        name: "artists"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "artists-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - {
              label: Artist Items,
              name: items,
              widget: list,
              fields:
                [
                  { label: Artist Name, name: title, widget: string },
                  { label: Image, name: image, widget: "image" },
                  { label: Url, name: url, widget: string },
                  { label: Text, name: text, widget: text },
                ],
            }
            # - {
            #     label: Intro,
            #     name: intro,
            #     widget: object,
            #     fields:
            #       [
            #         { label: Heading, name: heading, widget: string },
            #         { label: Description, name: description, widget: text },
            #         {
            #           label: Blurbs,
            #           name: blurbs,
            #           widget: list,
            #           fields:
            #             [
            #               { label: Image, name: image, widget: image },
            #               { label: Text, name: text, widget: text },
            #             ],
            #         },
            #       ],
            #   }
            # - {
            #     label: Main,
            #     name: main,
            #     widget: object,
            #     fields:
            #       [
            #         { label: Heading, name: heading, widget: string },
            #         { label: Description, name: description, widget: text },
            #         {
            #           label: Image1,
            #           name: image1,
            #           widget: object,
            #           fields:
            #             [
            #               { label: Image, name: image, widget: image },
            #               { label: Alt, name: alt, widget: string },
            #             ],
            #         },
            #         {
            #           label: Image2,
            #           name: image2,
            #           widget: object,
            #           fields:
            #             [
            #               { label: Image, name: image, widget: image },
            #               { label: Alt, name: alt, widget: string },
            #             ],
            #         },
            #         {
            #           label: Image3,
            #           name: image3,
            #           widget: object,
            #           fields:
            #             [
            #               { label: Image, name: image, widget: image },
            #               { label: Alt, name: alt, widget: string },
            #             ],
            #         },
            #       ],
            #   }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: "image" }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: "image" },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: "image" },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: "image" },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
